package com.eparking.informationPush.dao.sqlProvider;

import com.eparking.informationPush.entity.system.ParkInOut;
import com.eparking.informationPush.entity.system.ParkInOutCriteria.Criteria;
import com.eparking.informationPush.entity.system.ParkInOutCriteria.Criterion;
import com.eparking.informationPush.entity.system.ParkInOutCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ParkInOutSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    public String countByExample(ParkInOutCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("park_in_out");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    public String deleteByExample(ParkInOutCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("park_in_out");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    public String insertSelective(ParkInOut record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("park_in_out");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getActualPay() != null) {
            sql.VALUES("actual_pay", "#{actualPay,jdbcType=DOUBLE}");
        }
        
        if (record.getBeforePay() != null) {
            sql.VALUES("before_pay", "#{beforePay,jdbcType=DOUBLE}");
        }
        
        if (record.getCarNature() != null) {
            sql.VALUES("car_nature", "#{carNature,jdbcType=INTEGER}");
        }
        
        if (record.getChargeType() != null) {
            sql.VALUES("charge_type", "#{chargeType,jdbcType=INTEGER}");
        }
        
        if (record.getCoupon() != null) {
            sql.VALUES("coupon", "#{coupon,jdbcType=DOUBLE}");
        }
        
        if (record.getePayType() != null) {
            sql.VALUES("e_pay_type", "#{ePayType,jdbcType=INTEGER}");
        }
        
        if (record.getGovInUpFlag() != null) {
            sql.VALUES("gov_in_up_flag", "#{govInUpFlag,jdbcType=INTEGER}");
        }
        
        if (record.getGovOutUpFlag() != null) {
            sql.VALUES("gov_out_up_flag", "#{govOutUpFlag,jdbcType=INTEGER}");
        }
        
        if (record.getInCarPlate() != null) {
            sql.VALUES("in_car_plate", "#{inCarPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getInCarPlateColor() != null) {
            sql.VALUES("in_car_plate_color", "#{inCarPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getInPicPath() != null) {
            sql.VALUES("in_pic_path", "#{inPicPath,jdbcType=VARCHAR}");
        }
        
        if (record.getInPortId() != null) {
            sql.VALUES("in_port_id", "#{inPortId,jdbcType=INTEGER}");
        }
        
        if (record.getInPortName() != null) {
            sql.VALUES("in_port_name", "#{inPortName,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.VALUES("in_time", "#{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedPay() != null) {
            sql.VALUES("need_pay", "#{needPay,jdbcType=DOUBLE}");
        }
        
        if (record.getOccurTime() != null) {
            sql.VALUES("occur_time", "#{occurTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderId() != null) {
            sql.VALUES("order_id", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCarPlate() != null) {
            sql.VALUES("out_car_plate", "#{outCarPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCarPlateColor() != null) {
            sql.VALUES("out_car_plate_color", "#{outCarPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPicPath() != null) {
            sql.VALUES("out_pic_path", "#{outPicPath,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPortId() != null) {
            sql.VALUES("out_port_id", "#{outPortId,jdbcType=INTEGER}");
        }
        
        if (record.getOutPortName() != null) {
            sql.VALUES("out_port_name", "#{outPortName,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.VALUES("out_time", "#{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutType() != null) {
            sql.VALUES("out_type", "#{outType,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getQpassPay() != null) {
            sql.VALUES("qpass_pay", "#{qpassPay,jdbcType=DOUBLE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    public String selectByExample(ParkInOutCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("actual_pay");
        sql.SELECT("before_pay");
        sql.SELECT("car_nature");
        sql.SELECT("charge_type");
        sql.SELECT("coupon");
        sql.SELECT("e_pay_type");
        sql.SELECT("gov_in_up_flag");
        sql.SELECT("gov_out_up_flag");
        sql.SELECT("in_car_plate");
        sql.SELECT("in_car_plate_color");
        sql.SELECT("in_pic_path");
        sql.SELECT("in_port_id");
        sql.SELECT("in_port_name");
        sql.SELECT("in_time");
        sql.SELECT("need_pay");
        sql.SELECT("occur_time");
        sql.SELECT("order_id");
        sql.SELECT("out_car_plate");
        sql.SELECT("out_car_plate_color");
        sql.SELECT("out_pic_path");
        sql.SELECT("out_port_id");
        sql.SELECT("out_port_name");
        sql.SELECT("out_time");
        sql.SELECT("out_type");
        sql.SELECT("park_id");
        sql.SELECT("qpass_pay");
        sql.FROM("park_in_out");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ParkInOut record = (ParkInOut) parameter.get("record");
        ParkInOutCriteria example = (ParkInOutCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("park_in_out");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getActualPay() != null) {
            sql.SET("actual_pay = #{record.actualPay,jdbcType=DOUBLE}");
        }
        
        if (record.getBeforePay() != null) {
            sql.SET("before_pay = #{record.beforePay,jdbcType=DOUBLE}");
        }
        
        if (record.getCarNature() != null) {
            sql.SET("car_nature = #{record.carNature,jdbcType=INTEGER}");
        }
        
        if (record.getChargeType() != null) {
            sql.SET("charge_type = #{record.chargeType,jdbcType=INTEGER}");
        }
        
        if (record.getCoupon() != null) {
            sql.SET("coupon = #{record.coupon,jdbcType=DOUBLE}");
        }
        
        if (record.getePayType() != null) {
            sql.SET("e_pay_type = #{record.ePayType,jdbcType=INTEGER}");
        }
        
        if (record.getGovInUpFlag() != null) {
            sql.SET("gov_in_up_flag = #{record.govInUpFlag,jdbcType=INTEGER}");
        }
        
        if (record.getGovOutUpFlag() != null) {
            sql.SET("gov_out_up_flag = #{record.govOutUpFlag,jdbcType=INTEGER}");
        }
        
        if (record.getInCarPlate() != null) {
            sql.SET("in_car_plate = #{record.inCarPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getInCarPlateColor() != null) {
            sql.SET("in_car_plate_color = #{record.inCarPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getInPicPath() != null) {
            sql.SET("in_pic_path = #{record.inPicPath,jdbcType=VARCHAR}");
        }
        
        if (record.getInPortId() != null) {
            sql.SET("in_port_id = #{record.inPortId,jdbcType=INTEGER}");
        }
        
        if (record.getInPortName() != null) {
            sql.SET("in_port_name = #{record.inPortName,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedPay() != null) {
            sql.SET("need_pay = #{record.needPay,jdbcType=DOUBLE}");
        }
        
        if (record.getOccurTime() != null) {
            sql.SET("occur_time = #{record.occurTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCarPlate() != null) {
            sql.SET("out_car_plate = #{record.outCarPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCarPlateColor() != null) {
            sql.SET("out_car_plate_color = #{record.outCarPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPicPath() != null) {
            sql.SET("out_pic_path = #{record.outPicPath,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPortId() != null) {
            sql.SET("out_port_id = #{record.outPortId,jdbcType=INTEGER}");
        }
        
        if (record.getOutPortName() != null) {
            sql.SET("out_port_name = #{record.outPortName,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutType() != null) {
            sql.SET("out_type = #{record.outType,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getQpassPay() != null) {
            sql.SET("qpass_pay = #{record.qpassPay,jdbcType=DOUBLE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("park_in_out");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("actual_pay = #{record.actualPay,jdbcType=DOUBLE}");
        sql.SET("before_pay = #{record.beforePay,jdbcType=DOUBLE}");
        sql.SET("car_nature = #{record.carNature,jdbcType=INTEGER}");
        sql.SET("charge_type = #{record.chargeType,jdbcType=INTEGER}");
        sql.SET("coupon = #{record.coupon,jdbcType=DOUBLE}");
        sql.SET("e_pay_type = #{record.ePayType,jdbcType=INTEGER}");
        sql.SET("gov_in_up_flag = #{record.govInUpFlag,jdbcType=INTEGER}");
        sql.SET("gov_out_up_flag = #{record.govOutUpFlag,jdbcType=INTEGER}");
        sql.SET("in_car_plate = #{record.inCarPlate,jdbcType=VARCHAR}");
        sql.SET("in_car_plate_color = #{record.inCarPlateColor,jdbcType=VARCHAR}");
        sql.SET("in_pic_path = #{record.inPicPath,jdbcType=VARCHAR}");
        sql.SET("in_port_id = #{record.inPortId,jdbcType=INTEGER}");
        sql.SET("in_port_name = #{record.inPortName,jdbcType=VARCHAR}");
        sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        sql.SET("need_pay = #{record.needPay,jdbcType=DOUBLE}");
        sql.SET("occur_time = #{record.occurTime,jdbcType=VARCHAR}");
        sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        sql.SET("out_car_plate = #{record.outCarPlate,jdbcType=VARCHAR}");
        sql.SET("out_car_plate_color = #{record.outCarPlateColor,jdbcType=VARCHAR}");
        sql.SET("out_pic_path = #{record.outPicPath,jdbcType=VARCHAR}");
        sql.SET("out_port_id = #{record.outPortId,jdbcType=INTEGER}");
        sql.SET("out_port_name = #{record.outPortName,jdbcType=VARCHAR}");
        sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        sql.SET("out_type = #{record.outType,jdbcType=INTEGER}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("qpass_pay = #{record.qpassPay,jdbcType=DOUBLE}");
        
        ParkInOutCriteria example = (ParkInOutCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(ParkInOut record) {
        SQL sql = new SQL();
        sql.UPDATE("park_in_out");
        
        if (record.getActualPay() != null) {
            sql.SET("actual_pay = #{actualPay,jdbcType=DOUBLE}");
        }
        
        if (record.getBeforePay() != null) {
            sql.SET("before_pay = #{beforePay,jdbcType=DOUBLE}");
        }
        
        if (record.getCarNature() != null) {
            sql.SET("car_nature = #{carNature,jdbcType=INTEGER}");
        }
        
        if (record.getChargeType() != null) {
            sql.SET("charge_type = #{chargeType,jdbcType=INTEGER}");
        }
        
        if (record.getCoupon() != null) {
            sql.SET("coupon = #{coupon,jdbcType=DOUBLE}");
        }
        
        if (record.getePayType() != null) {
            sql.SET("e_pay_type = #{ePayType,jdbcType=INTEGER}");
        }
        
        if (record.getGovInUpFlag() != null) {
            sql.SET("gov_in_up_flag = #{govInUpFlag,jdbcType=INTEGER}");
        }
        
        if (record.getGovOutUpFlag() != null) {
            sql.SET("gov_out_up_flag = #{govOutUpFlag,jdbcType=INTEGER}");
        }
        
        if (record.getInCarPlate() != null) {
            sql.SET("in_car_plate = #{inCarPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getInCarPlateColor() != null) {
            sql.SET("in_car_plate_color = #{inCarPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getInPicPath() != null) {
            sql.SET("in_pic_path = #{inPicPath,jdbcType=VARCHAR}");
        }
        
        if (record.getInPortId() != null) {
            sql.SET("in_port_id = #{inPortId,jdbcType=INTEGER}");
        }
        
        if (record.getInPortName() != null) {
            sql.SET("in_port_name = #{inPortName,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedPay() != null) {
            sql.SET("need_pay = #{needPay,jdbcType=DOUBLE}");
        }
        
        if (record.getOccurTime() != null) {
            sql.SET("occur_time = #{occurTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCarPlate() != null) {
            sql.SET("out_car_plate = #{outCarPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCarPlateColor() != null) {
            sql.SET("out_car_plate_color = #{outCarPlateColor,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPicPath() != null) {
            sql.SET("out_pic_path = #{outPicPath,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPortId() != null) {
            sql.SET("out_port_id = #{outPortId,jdbcType=INTEGER}");
        }
        
        if (record.getOutPortName() != null) {
            sql.SET("out_port_name = #{outPortName,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutType() != null) {
            sql.SET("out_type = #{outType,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getQpassPay() != null) {
            sql.SET("qpass_pay = #{qpassPay,jdbcType=DOUBLE}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, ParkInOutCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}