package com.eparking.informationPush.dao.sqlProvider;

import com.eparking.informationPush.entity.system.ParkRouteConf;
import com.eparking.informationPush.entity.system.ParkRouteConfCriteria.Criteria;
import com.eparking.informationPush.entity.system.ParkRouteConfCriteria.Criterion;
import com.eparking.informationPush.entity.system.ParkRouteConfCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ParkRouteConfSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    public String countByExample(ParkRouteConfCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("park_route_conf");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    public String deleteByExample(ParkRouteConfCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("park_route_conf");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    public String insertSelective(ParkRouteConf record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("park_route_conf");
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getRouteId() != null) {
            sql.VALUES("route_id", "#{routeId,jdbcType=INTEGER}");
        }
        
        if (record.getRouteParkId() != null) {
            sql.VALUES("route_park_id", "#{routeParkId,jdbcType=VARCHAR}");
        }
        
        if (record.getRouteParkName() != null) {
            sql.VALUES("route_park_name", "#{routeParkName,jdbcType=VARCHAR}");
        }
        
        if (record.getInParkPort() != null) {
            sql.VALUES("in_park_port", "#{inParkPort,jdbcType=VARCHAR}");
        }
        
        if (record.getOutParkPort() != null) {
            sql.VALUES("out_park_port", "#{outParkPort,jdbcType=VARCHAR}");
        }
        
        if (record.getXkzh() != null) {
            sql.VALUES("xkzh", "#{xkzh,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKey() != null) {
            sql.VALUES("public_key", "#{publicKey,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    public String selectByExample(ParkRouteConfCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("park_id");
        } else {
            sql.SELECT("park_id");
        }
        sql.SELECT("route_id");
        sql.SELECT("route_park_id");
        sql.SELECT("route_park_name");
        sql.SELECT("in_park_port");
        sql.SELECT("out_park_port");
        sql.SELECT("xkzh");
        sql.SELECT("public_key");
        sql.FROM("park_route_conf");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ParkRouteConf record = (ParkRouteConf) parameter.get("record");
        ParkRouteConfCriteria example = (ParkRouteConfCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("park_route_conf");
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getRouteId() != null) {
            sql.SET("route_id = #{record.routeId,jdbcType=INTEGER}");
        }
        
        if (record.getRouteParkId() != null) {
            sql.SET("route_park_id = #{record.routeParkId,jdbcType=VARCHAR}");
        }
        
        if (record.getRouteParkName() != null) {
            sql.SET("route_park_name = #{record.routeParkName,jdbcType=VARCHAR}");
        }
        
        if (record.getInParkPort() != null) {
            sql.SET("in_park_port = #{record.inParkPort,jdbcType=VARCHAR}");
        }
        
        if (record.getOutParkPort() != null) {
            sql.SET("out_park_port = #{record.outParkPort,jdbcType=VARCHAR}");
        }
        
        if (record.getXkzh() != null) {
            sql.SET("xkzh = #{record.xkzh,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKey() != null) {
            sql.SET("public_key = #{record.publicKey,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("park_route_conf");
        
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("route_id = #{record.routeId,jdbcType=INTEGER}");
        sql.SET("route_park_id = #{record.routeParkId,jdbcType=VARCHAR}");
        sql.SET("route_park_name = #{record.routeParkName,jdbcType=VARCHAR}");
        sql.SET("in_park_port = #{record.inParkPort,jdbcType=VARCHAR}");
        sql.SET("out_park_port = #{record.outParkPort,jdbcType=VARCHAR}");
        sql.SET("xkzh = #{record.xkzh,jdbcType=VARCHAR}");
        sql.SET("public_key = #{record.publicKey,jdbcType=VARCHAR}");
        
        ParkRouteConfCriteria example = (ParkRouteConfCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(ParkRouteConf record) {
        SQL sql = new SQL();
        sql.UPDATE("park_route_conf");
        
        if (record.getRouteParkId() != null) {
            sql.SET("route_park_id = #{routeParkId,jdbcType=VARCHAR}");
        }
        
        if (record.getRouteParkName() != null) {
            sql.SET("route_park_name = #{routeParkName,jdbcType=VARCHAR}");
        }
        
        if (record.getInParkPort() != null) {
            sql.SET("in_park_port = #{inParkPort,jdbcType=VARCHAR}");
        }
        
        if (record.getOutParkPort() != null) {
            sql.SET("out_park_port = #{outParkPort,jdbcType=VARCHAR}");
        }
        
        if (record.getXkzh() != null) {
            sql.SET("xkzh = #{xkzh,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKey() != null) {
            sql.SET("public_key = #{publicKey,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("park_id = #{parkId,jdbcType=INTEGER}");
        sql.WHERE("route_id = #{routeId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_route_conf
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, ParkRouteConfCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}