package com.eparking.informationPush.dao.sqlProvider;

import com.eparking.informationPush.entity.system.RouteInfo;
import com.eparking.informationPush.entity.system.RouteInfoCriteria.Criteria;
import com.eparking.informationPush.entity.system.RouteInfoCriteria.Criterion;
import com.eparking.informationPush.entity.system.RouteInfoCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class RouteInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String countByExample(RouteInfoCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("route_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String deleteByExample(RouteInfoCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("route_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String insertSelective(RouteInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("route_info");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.VALUES("username", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            sql.VALUES("password", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getVerNum() != null) {
            sql.VALUES("ver_num", "#{verNum,jdbcType=VARCHAR}");
        }
        
        if (record.getServerIp() != null) {
            sql.VALUES("server_ip", "#{serverIp,jdbcType=VARCHAR}");
        }
        
        if (record.getServerPort() != null) {
            sql.VALUES("server_port", "#{serverPort,jdbcType=VARCHAR}");
        }
        
        if (record.getInPath() != null) {
            sql.VALUES("in_path", "#{inPath,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPath() != null) {
            sql.VALUES("out_path", "#{outPath,jdbcType=VARCHAR}");
        }
        
        if (record.getHeartPath() != null) {
            sql.VALUES("heart_path", "#{heartPath,jdbcType=VARCHAR}");
        }
        
        if (record.getStaticPath() != null) {
            sql.VALUES("static_path", "#{staticPath,jdbcType=VARCHAR}");
        }
        
        if (record.getDynamicPath() != null) {
            sql.VALUES("dynamic_path", "#{dynamicPath,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String selectByExample(RouteInfoCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("name");
        sql.SELECT("username");
        sql.SELECT("password");
        sql.SELECT("ver_num");
        sql.SELECT("server_ip");
        sql.SELECT("server_port");
        sql.SELECT("in_path");
        sql.SELECT("out_path");
        sql.SELECT("heart_path");
        sql.SELECT("static_path");
        sql.SELECT("dynamic_path");
        sql.FROM("route_info");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        RouteInfo record = (RouteInfo) parameter.get("record");
        RouteInfoCriteria example = (RouteInfoCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("route_info");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.SET("username = #{record.username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            sql.SET("password = #{record.password,jdbcType=VARCHAR}");
        }
        
        if (record.getVerNum() != null) {
            sql.SET("ver_num = #{record.verNum,jdbcType=VARCHAR}");
        }
        
        if (record.getServerIp() != null) {
            sql.SET("server_ip = #{record.serverIp,jdbcType=VARCHAR}");
        }
        
        if (record.getServerPort() != null) {
            sql.SET("server_port = #{record.serverPort,jdbcType=VARCHAR}");
        }
        
        if (record.getInPath() != null) {
            sql.SET("in_path = #{record.inPath,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPath() != null) {
            sql.SET("out_path = #{record.outPath,jdbcType=VARCHAR}");
        }
        
        if (record.getHeartPath() != null) {
            sql.SET("heart_path = #{record.heartPath,jdbcType=VARCHAR}");
        }
        
        if (record.getStaticPath() != null) {
            sql.SET("static_path = #{record.staticPath,jdbcType=VARCHAR}");
        }
        
        if (record.getDynamicPath() != null) {
            sql.SET("dynamic_path = #{record.dynamicPath,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("route_info");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("username = #{record.username,jdbcType=VARCHAR}");
        sql.SET("password = #{record.password,jdbcType=VARCHAR}");
        sql.SET("ver_num = #{record.verNum,jdbcType=VARCHAR}");
        sql.SET("server_ip = #{record.serverIp,jdbcType=VARCHAR}");
        sql.SET("server_port = #{record.serverPort,jdbcType=VARCHAR}");
        sql.SET("in_path = #{record.inPath,jdbcType=VARCHAR}");
        sql.SET("out_path = #{record.outPath,jdbcType=VARCHAR}");
        sql.SET("heart_path = #{record.heartPath,jdbcType=VARCHAR}");
        sql.SET("static_path = #{record.staticPath,jdbcType=VARCHAR}");
        sql.SET("dynamic_path = #{record.dynamicPath,jdbcType=VARCHAR}");
        
        RouteInfoCriteria example = (RouteInfoCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(RouteInfo record) {
        SQL sql = new SQL();
        sql.UPDATE("route_info");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getUsername() != null) {
            sql.SET("username = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            sql.SET("password = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getVerNum() != null) {
            sql.SET("ver_num = #{verNum,jdbcType=VARCHAR}");
        }
        
        if (record.getServerIp() != null) {
            sql.SET("server_ip = #{serverIp,jdbcType=VARCHAR}");
        }
        
        if (record.getServerPort() != null) {
            sql.SET("server_port = #{serverPort,jdbcType=VARCHAR}");
        }
        
        if (record.getInPath() != null) {
            sql.SET("in_path = #{inPath,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPath() != null) {
            sql.SET("out_path = #{outPath,jdbcType=VARCHAR}");
        }
        
        if (record.getHeartPath() != null) {
            sql.SET("heart_path = #{heartPath,jdbcType=VARCHAR}");
        }
        
        if (record.getStaticPath() != null) {
            sql.SET("static_path = #{staticPath,jdbcType=VARCHAR}");
        }
        
        if (record.getDynamicPath() != null) {
            sql.SET("dynamic_path = #{dynamicPath,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, RouteInfoCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}