package com.eparking.informationPush.entity.system;

import java.util.ArrayList;
import java.util.List;

public class ParkInOutCacheCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public ParkInOutCacheCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActualPayIsNull() {
            addCriterion("actual_pay is null");
            return (Criteria) this;
        }

        public Criteria andActualPayIsNotNull() {
            addCriterion("actual_pay is not null");
            return (Criteria) this;
        }

        public Criteria andActualPayEqualTo(Double value) {
            addCriterion("actual_pay =", value, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayNotEqualTo(Double value) {
            addCriterion("actual_pay <>", value, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayGreaterThan(Double value) {
            addCriterion("actual_pay >", value, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayGreaterThanOrEqualTo(Double value) {
            addCriterion("actual_pay >=", value, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayLessThan(Double value) {
            addCriterion("actual_pay <", value, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayLessThanOrEqualTo(Double value) {
            addCriterion("actual_pay <=", value, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayIn(List<Double> values) {
            addCriterion("actual_pay in", values, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayNotIn(List<Double> values) {
            addCriterion("actual_pay not in", values, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayBetween(Double value1, Double value2) {
            addCriterion("actual_pay between", value1, value2, "actualPay");
            return (Criteria) this;
        }

        public Criteria andActualPayNotBetween(Double value1, Double value2) {
            addCriterion("actual_pay not between", value1, value2, "actualPay");
            return (Criteria) this;
        }

        public Criteria andBeforePayIsNull() {
            addCriterion("before_pay is null");
            return (Criteria) this;
        }

        public Criteria andBeforePayIsNotNull() {
            addCriterion("before_pay is not null");
            return (Criteria) this;
        }

        public Criteria andBeforePayEqualTo(Double value) {
            addCriterion("before_pay =", value, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayNotEqualTo(Double value) {
            addCriterion("before_pay <>", value, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayGreaterThan(Double value) {
            addCriterion("before_pay >", value, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayGreaterThanOrEqualTo(Double value) {
            addCriterion("before_pay >=", value, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayLessThan(Double value) {
            addCriterion("before_pay <", value, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayLessThanOrEqualTo(Double value) {
            addCriterion("before_pay <=", value, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayIn(List<Double> values) {
            addCriterion("before_pay in", values, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayNotIn(List<Double> values) {
            addCriterion("before_pay not in", values, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayBetween(Double value1, Double value2) {
            addCriterion("before_pay between", value1, value2, "beforePay");
            return (Criteria) this;
        }

        public Criteria andBeforePayNotBetween(Double value1, Double value2) {
            addCriterion("before_pay not between", value1, value2, "beforePay");
            return (Criteria) this;
        }

        public Criteria andCarNatureIsNull() {
            addCriterion("car_nature is null");
            return (Criteria) this;
        }

        public Criteria andCarNatureIsNotNull() {
            addCriterion("car_nature is not null");
            return (Criteria) this;
        }

        public Criteria andCarNatureEqualTo(Integer value) {
            addCriterion("car_nature =", value, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureNotEqualTo(Integer value) {
            addCriterion("car_nature <>", value, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureGreaterThan(Integer value) {
            addCriterion("car_nature >", value, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_nature >=", value, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureLessThan(Integer value) {
            addCriterion("car_nature <", value, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureLessThanOrEqualTo(Integer value) {
            addCriterion("car_nature <=", value, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureIn(List<Integer> values) {
            addCriterion("car_nature in", values, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureNotIn(List<Integer> values) {
            addCriterion("car_nature not in", values, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureBetween(Integer value1, Integer value2) {
            addCriterion("car_nature between", value1, value2, "carNature");
            return (Criteria) this;
        }

        public Criteria andCarNatureNotBetween(Integer value1, Integer value2) {
            addCriterion("car_nature not between", value1, value2, "carNature");
            return (Criteria) this;
        }

        public Criteria andChargeTypeIsNull() {
            addCriterion("charge_type is null");
            return (Criteria) this;
        }

        public Criteria andChargeTypeIsNotNull() {
            addCriterion("charge_type is not null");
            return (Criteria) this;
        }

        public Criteria andChargeTypeEqualTo(Integer value) {
            addCriterion("charge_type =", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeNotEqualTo(Integer value) {
            addCriterion("charge_type <>", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeGreaterThan(Integer value) {
            addCriterion("charge_type >", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("charge_type >=", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeLessThan(Integer value) {
            addCriterion("charge_type <", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeLessThanOrEqualTo(Integer value) {
            addCriterion("charge_type <=", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeIn(List<Integer> values) {
            addCriterion("charge_type in", values, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeNotIn(List<Integer> values) {
            addCriterion("charge_type not in", values, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeBetween(Integer value1, Integer value2) {
            addCriterion("charge_type between", value1, value2, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("charge_type not between", value1, value2, "chargeType");
            return (Criteria) this;
        }

        public Criteria andCouponIsNull() {
            addCriterion("coupon is null");
            return (Criteria) this;
        }

        public Criteria andCouponIsNotNull() {
            addCriterion("coupon is not null");
            return (Criteria) this;
        }

        public Criteria andCouponEqualTo(Double value) {
            addCriterion("coupon =", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponNotEqualTo(Double value) {
            addCriterion("coupon <>", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponGreaterThan(Double value) {
            addCriterion("coupon >", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponGreaterThanOrEqualTo(Double value) {
            addCriterion("coupon >=", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponLessThan(Double value) {
            addCriterion("coupon <", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponLessThanOrEqualTo(Double value) {
            addCriterion("coupon <=", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponIn(List<Double> values) {
            addCriterion("coupon in", values, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponNotIn(List<Double> values) {
            addCriterion("coupon not in", values, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponBetween(Double value1, Double value2) {
            addCriterion("coupon between", value1, value2, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponNotBetween(Double value1, Double value2) {
            addCriterion("coupon not between", value1, value2, "coupon");
            return (Criteria) this;
        }

        public Criteria andEPayTypeIsNull() {
            addCriterion("e_pay_type is null");
            return (Criteria) this;
        }

        public Criteria andEPayTypeIsNotNull() {
            addCriterion("e_pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andEPayTypeEqualTo(Integer value) {
            addCriterion("e_pay_type =", value, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeNotEqualTo(Integer value) {
            addCriterion("e_pay_type <>", value, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeGreaterThan(Integer value) {
            addCriterion("e_pay_type >", value, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_pay_type >=", value, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeLessThan(Integer value) {
            addCriterion("e_pay_type <", value, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeLessThanOrEqualTo(Integer value) {
            addCriterion("e_pay_type <=", value, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeIn(List<Integer> values) {
            addCriterion("e_pay_type in", values, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeNotIn(List<Integer> values) {
            addCriterion("e_pay_type not in", values, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeBetween(Integer value1, Integer value2) {
            addCriterion("e_pay_type between", value1, value2, "ePayType");
            return (Criteria) this;
        }

        public Criteria andEPayTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("e_pay_type not between", value1, value2, "ePayType");
            return (Criteria) this;
        }

        public Criteria andInCarPlateIsNull() {
            addCriterion("in_car_plate is null");
            return (Criteria) this;
        }

        public Criteria andInCarPlateIsNotNull() {
            addCriterion("in_car_plate is not null");
            return (Criteria) this;
        }

        public Criteria andInCarPlateEqualTo(String value) {
            addCriterion("in_car_plate =", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateNotEqualTo(String value) {
            addCriterion("in_car_plate <>", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateGreaterThan(String value) {
            addCriterion("in_car_plate >", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateGreaterThanOrEqualTo(String value) {
            addCriterion("in_car_plate >=", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateLessThan(String value) {
            addCriterion("in_car_plate <", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateLessThanOrEqualTo(String value) {
            addCriterion("in_car_plate <=", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateLike(String value) {
            addCriterion("in_car_plate like", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateNotLike(String value) {
            addCriterion("in_car_plate not like", value, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateIn(List<String> values) {
            addCriterion("in_car_plate in", values, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateNotIn(List<String> values) {
            addCriterion("in_car_plate not in", values, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateBetween(String value1, String value2) {
            addCriterion("in_car_plate between", value1, value2, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateNotBetween(String value1, String value2) {
            addCriterion("in_car_plate not between", value1, value2, "inCarPlate");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorIsNull() {
            addCriterion("in_car_plate_color is null");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorIsNotNull() {
            addCriterion("in_car_plate_color is not null");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorEqualTo(String value) {
            addCriterion("in_car_plate_color =", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorNotEqualTo(String value) {
            addCriterion("in_car_plate_color <>", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorGreaterThan(String value) {
            addCriterion("in_car_plate_color >", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorGreaterThanOrEqualTo(String value) {
            addCriterion("in_car_plate_color >=", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorLessThan(String value) {
            addCriterion("in_car_plate_color <", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorLessThanOrEqualTo(String value) {
            addCriterion("in_car_plate_color <=", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorLike(String value) {
            addCriterion("in_car_plate_color like", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorNotLike(String value) {
            addCriterion("in_car_plate_color not like", value, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorIn(List<String> values) {
            addCriterion("in_car_plate_color in", values, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorNotIn(List<String> values) {
            addCriterion("in_car_plate_color not in", values, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorBetween(String value1, String value2) {
            addCriterion("in_car_plate_color between", value1, value2, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInCarPlateColorNotBetween(String value1, String value2) {
            addCriterion("in_car_plate_color not between", value1, value2, "inCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andInPicPathIsNull() {
            addCriterion("in_pic_path is null");
            return (Criteria) this;
        }

        public Criteria andInPicPathIsNotNull() {
            addCriterion("in_pic_path is not null");
            return (Criteria) this;
        }

        public Criteria andInPicPathEqualTo(String value) {
            addCriterion("in_pic_path =", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathNotEqualTo(String value) {
            addCriterion("in_pic_path <>", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathGreaterThan(String value) {
            addCriterion("in_pic_path >", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathGreaterThanOrEqualTo(String value) {
            addCriterion("in_pic_path >=", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathLessThan(String value) {
            addCriterion("in_pic_path <", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathLessThanOrEqualTo(String value) {
            addCriterion("in_pic_path <=", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathLike(String value) {
            addCriterion("in_pic_path like", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathNotLike(String value) {
            addCriterion("in_pic_path not like", value, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathIn(List<String> values) {
            addCriterion("in_pic_path in", values, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathNotIn(List<String> values) {
            addCriterion("in_pic_path not in", values, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathBetween(String value1, String value2) {
            addCriterion("in_pic_path between", value1, value2, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPicPathNotBetween(String value1, String value2) {
            addCriterion("in_pic_path not between", value1, value2, "inPicPath");
            return (Criteria) this;
        }

        public Criteria andInPortIdIsNull() {
            addCriterion("in_port_id is null");
            return (Criteria) this;
        }

        public Criteria andInPortIdIsNotNull() {
            addCriterion("in_port_id is not null");
            return (Criteria) this;
        }

        public Criteria andInPortIdEqualTo(Integer value) {
            addCriterion("in_port_id =", value, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdNotEqualTo(Integer value) {
            addCriterion("in_port_id <>", value, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdGreaterThan(Integer value) {
            addCriterion("in_port_id >", value, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("in_port_id >=", value, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdLessThan(Integer value) {
            addCriterion("in_port_id <", value, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdLessThanOrEqualTo(Integer value) {
            addCriterion("in_port_id <=", value, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdIn(List<Integer> values) {
            addCriterion("in_port_id in", values, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdNotIn(List<Integer> values) {
            addCriterion("in_port_id not in", values, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdBetween(Integer value1, Integer value2) {
            addCriterion("in_port_id between", value1, value2, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortIdNotBetween(Integer value1, Integer value2) {
            addCriterion("in_port_id not between", value1, value2, "inPortId");
            return (Criteria) this;
        }

        public Criteria andInPortNameIsNull() {
            addCriterion("in_port_name is null");
            return (Criteria) this;
        }

        public Criteria andInPortNameIsNotNull() {
            addCriterion("in_port_name is not null");
            return (Criteria) this;
        }

        public Criteria andInPortNameEqualTo(String value) {
            addCriterion("in_port_name =", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameNotEqualTo(String value) {
            addCriterion("in_port_name <>", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameGreaterThan(String value) {
            addCriterion("in_port_name >", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameGreaterThanOrEqualTo(String value) {
            addCriterion("in_port_name >=", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameLessThan(String value) {
            addCriterion("in_port_name <", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameLessThanOrEqualTo(String value) {
            addCriterion("in_port_name <=", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameLike(String value) {
            addCriterion("in_port_name like", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameNotLike(String value) {
            addCriterion("in_port_name not like", value, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameIn(List<String> values) {
            addCriterion("in_port_name in", values, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameNotIn(List<String> values) {
            addCriterion("in_port_name not in", values, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameBetween(String value1, String value2) {
            addCriterion("in_port_name between", value1, value2, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInPortNameNotBetween(String value1, String value2) {
            addCriterion("in_port_name not between", value1, value2, "inPortName");
            return (Criteria) this;
        }

        public Criteria andInTimeIsNull() {
            addCriterion("in_time is null");
            return (Criteria) this;
        }

        public Criteria andInTimeIsNotNull() {
            addCriterion("in_time is not null");
            return (Criteria) this;
        }

        public Criteria andInTimeEqualTo(String value) {
            addCriterion("in_time =", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeNotEqualTo(String value) {
            addCriterion("in_time <>", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeGreaterThan(String value) {
            addCriterion("in_time >", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeGreaterThanOrEqualTo(String value) {
            addCriterion("in_time >=", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeLessThan(String value) {
            addCriterion("in_time <", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeLessThanOrEqualTo(String value) {
            addCriterion("in_time <=", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeLike(String value) {
            addCriterion("in_time like", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeNotLike(String value) {
            addCriterion("in_time not like", value, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeIn(List<String> values) {
            addCriterion("in_time in", values, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeNotIn(List<String> values) {
            addCriterion("in_time not in", values, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeBetween(String value1, String value2) {
            addCriterion("in_time between", value1, value2, "inTime");
            return (Criteria) this;
        }

        public Criteria andInTimeNotBetween(String value1, String value2) {
            addCriterion("in_time not between", value1, value2, "inTime");
            return (Criteria) this;
        }

        public Criteria andNeedPayIsNull() {
            addCriterion("need_pay is null");
            return (Criteria) this;
        }

        public Criteria andNeedPayIsNotNull() {
            addCriterion("need_pay is not null");
            return (Criteria) this;
        }

        public Criteria andNeedPayEqualTo(Double value) {
            addCriterion("need_pay =", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayNotEqualTo(Double value) {
            addCriterion("need_pay <>", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayGreaterThan(Double value) {
            addCriterion("need_pay >", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayGreaterThanOrEqualTo(Double value) {
            addCriterion("need_pay >=", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayLessThan(Double value) {
            addCriterion("need_pay <", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayLessThanOrEqualTo(Double value) {
            addCriterion("need_pay <=", value, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayIn(List<Double> values) {
            addCriterion("need_pay in", values, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayNotIn(List<Double> values) {
            addCriterion("need_pay not in", values, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayBetween(Double value1, Double value2) {
            addCriterion("need_pay between", value1, value2, "needPay");
            return (Criteria) this;
        }

        public Criteria andNeedPayNotBetween(Double value1, Double value2) {
            addCriterion("need_pay not between", value1, value2, "needPay");
            return (Criteria) this;
        }

        public Criteria andOccurTimeIsNull() {
            addCriterion("occur_time is null");
            return (Criteria) this;
        }

        public Criteria andOccurTimeIsNotNull() {
            addCriterion("occur_time is not null");
            return (Criteria) this;
        }

        public Criteria andOccurTimeEqualTo(String value) {
            addCriterion("occur_time =", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeNotEqualTo(String value) {
            addCriterion("occur_time <>", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeGreaterThan(String value) {
            addCriterion("occur_time >", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeGreaterThanOrEqualTo(String value) {
            addCriterion("occur_time >=", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeLessThan(String value) {
            addCriterion("occur_time <", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeLessThanOrEqualTo(String value) {
            addCriterion("occur_time <=", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeLike(String value) {
            addCriterion("occur_time like", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeNotLike(String value) {
            addCriterion("occur_time not like", value, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeIn(List<String> values) {
            addCriterion("occur_time in", values, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeNotIn(List<String> values) {
            addCriterion("occur_time not in", values, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeBetween(String value1, String value2) {
            addCriterion("occur_time between", value1, value2, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOccurTimeNotBetween(String value1, String value2) {
            addCriterion("occur_time not between", value1, value2, "occurTime");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateIsNull() {
            addCriterion("out_car_plate is null");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateIsNotNull() {
            addCriterion("out_car_plate is not null");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateEqualTo(String value) {
            addCriterion("out_car_plate =", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateNotEqualTo(String value) {
            addCriterion("out_car_plate <>", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateGreaterThan(String value) {
            addCriterion("out_car_plate >", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateGreaterThanOrEqualTo(String value) {
            addCriterion("out_car_plate >=", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateLessThan(String value) {
            addCriterion("out_car_plate <", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateLessThanOrEqualTo(String value) {
            addCriterion("out_car_plate <=", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateLike(String value) {
            addCriterion("out_car_plate like", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateNotLike(String value) {
            addCriterion("out_car_plate not like", value, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateIn(List<String> values) {
            addCriterion("out_car_plate in", values, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateNotIn(List<String> values) {
            addCriterion("out_car_plate not in", values, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateBetween(String value1, String value2) {
            addCriterion("out_car_plate between", value1, value2, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateNotBetween(String value1, String value2) {
            addCriterion("out_car_plate not between", value1, value2, "outCarPlate");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorIsNull() {
            addCriterion("out_car_plate_color is null");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorIsNotNull() {
            addCriterion("out_car_plate_color is not null");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorEqualTo(String value) {
            addCriterion("out_car_plate_color =", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorNotEqualTo(String value) {
            addCriterion("out_car_plate_color <>", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorGreaterThan(String value) {
            addCriterion("out_car_plate_color >", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorGreaterThanOrEqualTo(String value) {
            addCriterion("out_car_plate_color >=", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorLessThan(String value) {
            addCriterion("out_car_plate_color <", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorLessThanOrEqualTo(String value) {
            addCriterion("out_car_plate_color <=", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorLike(String value) {
            addCriterion("out_car_plate_color like", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorNotLike(String value) {
            addCriterion("out_car_plate_color not like", value, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorIn(List<String> values) {
            addCriterion("out_car_plate_color in", values, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorNotIn(List<String> values) {
            addCriterion("out_car_plate_color not in", values, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorBetween(String value1, String value2) {
            addCriterion("out_car_plate_color between", value1, value2, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutCarPlateColorNotBetween(String value1, String value2) {
            addCriterion("out_car_plate_color not between", value1, value2, "outCarPlateColor");
            return (Criteria) this;
        }

        public Criteria andOutPicPathIsNull() {
            addCriterion("out_pic_path is null");
            return (Criteria) this;
        }

        public Criteria andOutPicPathIsNotNull() {
            addCriterion("out_pic_path is not null");
            return (Criteria) this;
        }

        public Criteria andOutPicPathEqualTo(String value) {
            addCriterion("out_pic_path =", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathNotEqualTo(String value) {
            addCriterion("out_pic_path <>", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathGreaterThan(String value) {
            addCriterion("out_pic_path >", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathGreaterThanOrEqualTo(String value) {
            addCriterion("out_pic_path >=", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathLessThan(String value) {
            addCriterion("out_pic_path <", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathLessThanOrEqualTo(String value) {
            addCriterion("out_pic_path <=", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathLike(String value) {
            addCriterion("out_pic_path like", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathNotLike(String value) {
            addCriterion("out_pic_path not like", value, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathIn(List<String> values) {
            addCriterion("out_pic_path in", values, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathNotIn(List<String> values) {
            addCriterion("out_pic_path not in", values, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathBetween(String value1, String value2) {
            addCriterion("out_pic_path between", value1, value2, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPicPathNotBetween(String value1, String value2) {
            addCriterion("out_pic_path not between", value1, value2, "outPicPath");
            return (Criteria) this;
        }

        public Criteria andOutPortIdIsNull() {
            addCriterion("out_port_id is null");
            return (Criteria) this;
        }

        public Criteria andOutPortIdIsNotNull() {
            addCriterion("out_port_id is not null");
            return (Criteria) this;
        }

        public Criteria andOutPortIdEqualTo(Integer value) {
            addCriterion("out_port_id =", value, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdNotEqualTo(Integer value) {
            addCriterion("out_port_id <>", value, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdGreaterThan(Integer value) {
            addCriterion("out_port_id >", value, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("out_port_id >=", value, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdLessThan(Integer value) {
            addCriterion("out_port_id <", value, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdLessThanOrEqualTo(Integer value) {
            addCriterion("out_port_id <=", value, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdIn(List<Integer> values) {
            addCriterion("out_port_id in", values, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdNotIn(List<Integer> values) {
            addCriterion("out_port_id not in", values, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdBetween(Integer value1, Integer value2) {
            addCriterion("out_port_id between", value1, value2, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortIdNotBetween(Integer value1, Integer value2) {
            addCriterion("out_port_id not between", value1, value2, "outPortId");
            return (Criteria) this;
        }

        public Criteria andOutPortNameIsNull() {
            addCriterion("out_port_name is null");
            return (Criteria) this;
        }

        public Criteria andOutPortNameIsNotNull() {
            addCriterion("out_port_name is not null");
            return (Criteria) this;
        }

        public Criteria andOutPortNameEqualTo(String value) {
            addCriterion("out_port_name =", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameNotEqualTo(String value) {
            addCriterion("out_port_name <>", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameGreaterThan(String value) {
            addCriterion("out_port_name >", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameGreaterThanOrEqualTo(String value) {
            addCriterion("out_port_name >=", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameLessThan(String value) {
            addCriterion("out_port_name <", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameLessThanOrEqualTo(String value) {
            addCriterion("out_port_name <=", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameLike(String value) {
            addCriterion("out_port_name like", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameNotLike(String value) {
            addCriterion("out_port_name not like", value, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameIn(List<String> values) {
            addCriterion("out_port_name in", values, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameNotIn(List<String> values) {
            addCriterion("out_port_name not in", values, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameBetween(String value1, String value2) {
            addCriterion("out_port_name between", value1, value2, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutPortNameNotBetween(String value1, String value2) {
            addCriterion("out_port_name not between", value1, value2, "outPortName");
            return (Criteria) this;
        }

        public Criteria andOutTimeIsNull() {
            addCriterion("out_time is null");
            return (Criteria) this;
        }

        public Criteria andOutTimeIsNotNull() {
            addCriterion("out_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutTimeEqualTo(String value) {
            addCriterion("out_time =", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotEqualTo(String value) {
            addCriterion("out_time <>", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeGreaterThan(String value) {
            addCriterion("out_time >", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeGreaterThanOrEqualTo(String value) {
            addCriterion("out_time >=", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLessThan(String value) {
            addCriterion("out_time <", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLessThanOrEqualTo(String value) {
            addCriterion("out_time <=", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLike(String value) {
            addCriterion("out_time like", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotLike(String value) {
            addCriterion("out_time not like", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeIn(List<String> values) {
            addCriterion("out_time in", values, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotIn(List<String> values) {
            addCriterion("out_time not in", values, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeBetween(String value1, String value2) {
            addCriterion("out_time between", value1, value2, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotBetween(String value1, String value2) {
            addCriterion("out_time not between", value1, value2, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTypeIsNull() {
            addCriterion("out_type is null");
            return (Criteria) this;
        }

        public Criteria andOutTypeIsNotNull() {
            addCriterion("out_type is not null");
            return (Criteria) this;
        }

        public Criteria andOutTypeEqualTo(Integer value) {
            addCriterion("out_type =", value, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeNotEqualTo(Integer value) {
            addCriterion("out_type <>", value, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeGreaterThan(Integer value) {
            addCriterion("out_type >", value, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("out_type >=", value, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeLessThan(Integer value) {
            addCriterion("out_type <", value, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeLessThanOrEqualTo(Integer value) {
            addCriterion("out_type <=", value, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeIn(List<Integer> values) {
            addCriterion("out_type in", values, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeNotIn(List<Integer> values) {
            addCriterion("out_type not in", values, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeBetween(Integer value1, Integer value2) {
            addCriterion("out_type between", value1, value2, "outType");
            return (Criteria) this;
        }

        public Criteria andOutTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("out_type not between", value1, value2, "outType");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNull() {
            addCriterion("park_id is null");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNotNull() {
            addCriterion("park_id is not null");
            return (Criteria) this;
        }

        public Criteria andParkIdEqualTo(Integer value) {
            addCriterion("park_id =", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotEqualTo(Integer value) {
            addCriterion("park_id <>", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThan(Integer value) {
            addCriterion("park_id >", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("park_id >=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThan(Integer value) {
            addCriterion("park_id <", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThanOrEqualTo(Integer value) {
            addCriterion("park_id <=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdIn(List<Integer> values) {
            addCriterion("park_id in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotIn(List<Integer> values) {
            addCriterion("park_id not in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdBetween(Integer value1, Integer value2) {
            addCriterion("park_id between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("park_id not between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andQpassPayIsNull() {
            addCriterion("qpass_pay is null");
            return (Criteria) this;
        }

        public Criteria andQpassPayIsNotNull() {
            addCriterion("qpass_pay is not null");
            return (Criteria) this;
        }

        public Criteria andQpassPayEqualTo(Double value) {
            addCriterion("qpass_pay =", value, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayNotEqualTo(Double value) {
            addCriterion("qpass_pay <>", value, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayGreaterThan(Double value) {
            addCriterion("qpass_pay >", value, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayGreaterThanOrEqualTo(Double value) {
            addCriterion("qpass_pay >=", value, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayLessThan(Double value) {
            addCriterion("qpass_pay <", value, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayLessThanOrEqualTo(Double value) {
            addCriterion("qpass_pay <=", value, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayIn(List<Double> values) {
            addCriterion("qpass_pay in", values, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayNotIn(List<Double> values) {
            addCriterion("qpass_pay not in", values, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayBetween(Double value1, Double value2) {
            addCriterion("qpass_pay between", value1, value2, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andQpassPayNotBetween(Double value1, Double value2) {
            addCriterion("qpass_pay not between", value1, value2, "qpassPay");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNull() {
            addCriterion("route_id is null");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNotNull() {
            addCriterion("route_id is not null");
            return (Criteria) this;
        }

        public Criteria andRouteIdEqualTo(Integer value) {
            addCriterion("route_id =", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotEqualTo(Integer value) {
            addCriterion("route_id <>", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThan(Integer value) {
            addCriterion("route_id >", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_id >=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThan(Integer value) {
            addCriterion("route_id <", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThanOrEqualTo(Integer value) {
            addCriterion("route_id <=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIn(List<Integer> values) {
            addCriterion("route_id in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotIn(List<Integer> values) {
            addCriterion("route_id not in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdBetween(Integer value1, Integer value2) {
            addCriterion("route_id between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("route_id not between", value1, value2, "routeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table park_in_out_cache
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table park_in_out_cache
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}