package com.eparking.informationPush.entity.system;

public class ParkRouteConf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.route_id
     *
     * @mbg.generated
     */
    private Integer routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.route_park_id
     *
     * @mbg.generated
     */
    private String routeParkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.route_park_name
     *
     * @mbg.generated
     */
    private String routeParkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.in_park_port
     *
     * @mbg.generated
     */
    private String inParkPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.out_park_port
     *
     * @mbg.generated
     */
    private String outParkPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.xkzh
     *
     * @mbg.generated
     */
    private String xkzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_route_conf.public_key
     *
     * @mbg.generated
     */
    private String publicKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.park_id
     *
     * @return the value of park_route_conf.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.park_id
     *
     * @param parkId the value for park_route_conf.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.route_id
     *
     * @return the value of park_route_conf.route_id
     *
     * @mbg.generated
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.route_id
     *
     * @param routeId the value for park_route_conf.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.route_park_id
     *
     * @return the value of park_route_conf.route_park_id
     *
     * @mbg.generated
     */
    public String getRouteParkId() {
        return routeParkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.route_park_id
     *
     * @param routeParkId the value for park_route_conf.route_park_id
     *
     * @mbg.generated
     */
    public void setRouteParkId(String routeParkId) {
        this.routeParkId = routeParkId == null ? null : routeParkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.route_park_name
     *
     * @return the value of park_route_conf.route_park_name
     *
     * @mbg.generated
     */
    public String getRouteParkName() {
        return routeParkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.route_park_name
     *
     * @param routeParkName the value for park_route_conf.route_park_name
     *
     * @mbg.generated
     */
    public void setRouteParkName(String routeParkName) {
        this.routeParkName = routeParkName == null ? null : routeParkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.in_park_port
     *
     * @return the value of park_route_conf.in_park_port
     *
     * @mbg.generated
     */
    public String getInParkPort() {
        return inParkPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.in_park_port
     *
     * @param inParkPort the value for park_route_conf.in_park_port
     *
     * @mbg.generated
     */
    public void setInParkPort(String inParkPort) {
        this.inParkPort = inParkPort == null ? null : inParkPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.out_park_port
     *
     * @return the value of park_route_conf.out_park_port
     *
     * @mbg.generated
     */
    public String getOutParkPort() {
        return outParkPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.out_park_port
     *
     * @param outParkPort the value for park_route_conf.out_park_port
     *
     * @mbg.generated
     */
    public void setOutParkPort(String outParkPort) {
        this.outParkPort = outParkPort == null ? null : outParkPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.xkzh
     *
     * @return the value of park_route_conf.xkzh
     *
     * @mbg.generated
     */
    public String getXkzh() {
        return xkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.xkzh
     *
     * @param xkzh the value for park_route_conf.xkzh
     *
     * @mbg.generated
     */
    public void setXkzh(String xkzh) {
        this.xkzh = xkzh == null ? null : xkzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_route_conf.public_key
     *
     * @return the value of park_route_conf.public_key
     *
     * @mbg.generated
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_route_conf.public_key
     *
     * @param publicKey the value for park_route_conf.public_key
     *
     * @mbg.generated
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey == null ? null : publicKey.trim();
    }
}