package com.eparking.informationPush.entity.system;

public class ParkPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_permission.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_permission.park_name
     *
     * @mbg.generated
     */
    private String parkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_permission.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_permission.route_ids
     *
     * @mbg.generated
     */
    private String routeIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_permission.id
     *
     * @return the value of park_permission.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_permission.id
     *
     * @param id the value for park_permission.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_permission.park_name
     *
     * @return the value of park_permission.park_name
     *
     * @mbg.generated
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_permission.park_name
     *
     * @param parkName the value for park_permission.park_name
     *
     * @mbg.generated
     */
    public void setParkName(String parkName) {
        this.parkName = parkName == null ? null : parkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_permission.status
     *
     * @return the value of park_permission.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_permission.status
     *
     * @param status the value for park_permission.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_permission.route_ids
     *
     * @return the value of park_permission.route_ids
     *
     * @mbg.generated
     */
    public String getRouteIds() {
        return routeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_permission.route_ids
     *
     * @param routeIds the value for park_permission.route_ids
     *
     * @mbg.generated
     */
    public void setRouteIds(String routeIds) {
        this.routeIds = routeIds == null ? null : routeIds.trim();
    }
}