package com.eparking.informationPush.entity.system;

public class ParkInOut {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.actual_pay
     *
     * @mbg.generated
     */
    private Double actualPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.before_pay
     *
     * @mbg.generated
     */
    private Double beforePay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.car_nature
     *
     * @mbg.generated
     */
    private Integer carNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.charge_type
     *
     * @mbg.generated
     */
    private Integer chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.coupon
     *
     * @mbg.generated
     */
    private Double coupon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.e_pay_type
     *
     * @mbg.generated
     */
    private Integer ePayType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.gov_in_up_flag
     *
     * @mbg.generated
     */
    private Integer govInUpFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.gov_out_up_flag
     *
     * @mbg.generated
     */
    private Integer govOutUpFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.in_car_plate
     *
     * @mbg.generated
     */
    private String inCarPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.in_car_plate_color
     *
     * @mbg.generated
     */
    private String inCarPlateColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.in_pic_path
     *
     * @mbg.generated
     */
    private String inPicPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.in_port_id
     *
     * @mbg.generated
     */
    private Integer inPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.in_port_name
     *
     * @mbg.generated
     */
    private String inPortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.in_time
     *
     * @mbg.generated
     */
    private String inTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.need_pay
     *
     * @mbg.generated
     */
    private Double needPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.occur_time
     *
     * @mbg.generated
     */
    private String occurTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.out_car_plate
     *
     * @mbg.generated
     */
    private String outCarPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.out_car_plate_color
     *
     * @mbg.generated
     */
    private String outCarPlateColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.out_pic_path
     *
     * @mbg.generated
     */
    private String outPicPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.out_port_id
     *
     * @mbg.generated
     */
    private Integer outPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.out_port_name
     *
     * @mbg.generated
     */
    private String outPortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.out_time
     *
     * @mbg.generated
     */
    private String outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.out_type
     *
     * @mbg.generated
     */
    private Integer outType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column park_in_out.qpass_pay
     *
     * @mbg.generated
     */
    private Double qpassPay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.id
     *
     * @return the value of park_in_out.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.id
     *
     * @param id the value for park_in_out.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.actual_pay
     *
     * @return the value of park_in_out.actual_pay
     *
     * @mbg.generated
     */
    public Double getActualPay() {
        return actualPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.actual_pay
     *
     * @param actualPay the value for park_in_out.actual_pay
     *
     * @mbg.generated
     */
    public void setActualPay(Double actualPay) {
        this.actualPay = actualPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.before_pay
     *
     * @return the value of park_in_out.before_pay
     *
     * @mbg.generated
     */
    public Double getBeforePay() {
        return beforePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.before_pay
     *
     * @param beforePay the value for park_in_out.before_pay
     *
     * @mbg.generated
     */
    public void setBeforePay(Double beforePay) {
        this.beforePay = beforePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.car_nature
     *
     * @return the value of park_in_out.car_nature
     *
     * @mbg.generated
     */
    public Integer getCarNature() {
        return carNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.car_nature
     *
     * @param carNature the value for park_in_out.car_nature
     *
     * @mbg.generated
     */
    public void setCarNature(Integer carNature) {
        this.carNature = carNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.charge_type
     *
     * @return the value of park_in_out.charge_type
     *
     * @mbg.generated
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.charge_type
     *
     * @param chargeType the value for park_in_out.charge_type
     *
     * @mbg.generated
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.coupon
     *
     * @return the value of park_in_out.coupon
     *
     * @mbg.generated
     */
    public Double getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.coupon
     *
     * @param coupon the value for park_in_out.coupon
     *
     * @mbg.generated
     */
    public void setCoupon(Double coupon) {
        this.coupon = coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.e_pay_type
     *
     * @return the value of park_in_out.e_pay_type
     *
     * @mbg.generated
     */
    public Integer getePayType() {
        return ePayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.e_pay_type
     *
     * @param ePayType the value for park_in_out.e_pay_type
     *
     * @mbg.generated
     */
    public void setePayType(Integer ePayType) {
        this.ePayType = ePayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.gov_in_up_flag
     *
     * @return the value of park_in_out.gov_in_up_flag
     *
     * @mbg.generated
     */
    public Integer getGovInUpFlag() {
        return govInUpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.gov_in_up_flag
     *
     * @param govInUpFlag the value for park_in_out.gov_in_up_flag
     *
     * @mbg.generated
     */
    public void setGovInUpFlag(Integer govInUpFlag) {
        this.govInUpFlag = govInUpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.gov_out_up_flag
     *
     * @return the value of park_in_out.gov_out_up_flag
     *
     * @mbg.generated
     */
    public Integer getGovOutUpFlag() {
        return govOutUpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.gov_out_up_flag
     *
     * @param govOutUpFlag the value for park_in_out.gov_out_up_flag
     *
     * @mbg.generated
     */
    public void setGovOutUpFlag(Integer govOutUpFlag) {
        this.govOutUpFlag = govOutUpFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.in_car_plate
     *
     * @return the value of park_in_out.in_car_plate
     *
     * @mbg.generated
     */
    public String getInCarPlate() {
        return inCarPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.in_car_plate
     *
     * @param inCarPlate the value for park_in_out.in_car_plate
     *
     * @mbg.generated
     */
    public void setInCarPlate(String inCarPlate) {
        this.inCarPlate = inCarPlate == null ? null : inCarPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.in_car_plate_color
     *
     * @return the value of park_in_out.in_car_plate_color
     *
     * @mbg.generated
     */
    public String getInCarPlateColor() {
        return inCarPlateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.in_car_plate_color
     *
     * @param inCarPlateColor the value for park_in_out.in_car_plate_color
     *
     * @mbg.generated
     */
    public void setInCarPlateColor(String inCarPlateColor) {
        this.inCarPlateColor = inCarPlateColor == null ? null : inCarPlateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.in_pic_path
     *
     * @return the value of park_in_out.in_pic_path
     *
     * @mbg.generated
     */
    public String getInPicPath() {
        return inPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.in_pic_path
     *
     * @param inPicPath the value for park_in_out.in_pic_path
     *
     * @mbg.generated
     */
    public void setInPicPath(String inPicPath) {
        this.inPicPath = inPicPath == null ? null : inPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.in_port_id
     *
     * @return the value of park_in_out.in_port_id
     *
     * @mbg.generated
     */
    public Integer getInPortId() {
        return inPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.in_port_id
     *
     * @param inPortId the value for park_in_out.in_port_id
     *
     * @mbg.generated
     */
    public void setInPortId(Integer inPortId) {
        this.inPortId = inPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.in_port_name
     *
     * @return the value of park_in_out.in_port_name
     *
     * @mbg.generated
     */
    public String getInPortName() {
        return inPortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.in_port_name
     *
     * @param inPortName the value for park_in_out.in_port_name
     *
     * @mbg.generated
     */
    public void setInPortName(String inPortName) {
        this.inPortName = inPortName == null ? null : inPortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.in_time
     *
     * @return the value of park_in_out.in_time
     *
     * @mbg.generated
     */
    public String getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.in_time
     *
     * @param inTime the value for park_in_out.in_time
     *
     * @mbg.generated
     */
    public void setInTime(String inTime) {
        this.inTime = inTime == null ? null : inTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.need_pay
     *
     * @return the value of park_in_out.need_pay
     *
     * @mbg.generated
     */
    public Double getNeedPay() {
        return needPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.need_pay
     *
     * @param needPay the value for park_in_out.need_pay
     *
     * @mbg.generated
     */
    public void setNeedPay(Double needPay) {
        this.needPay = needPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.occur_time
     *
     * @return the value of park_in_out.occur_time
     *
     * @mbg.generated
     */
    public String getOccurTime() {
        return occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.occur_time
     *
     * @param occurTime the value for park_in_out.occur_time
     *
     * @mbg.generated
     */
    public void setOccurTime(String occurTime) {
        this.occurTime = occurTime == null ? null : occurTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.order_id
     *
     * @return the value of park_in_out.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.order_id
     *
     * @param orderId the value for park_in_out.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.out_car_plate
     *
     * @return the value of park_in_out.out_car_plate
     *
     * @mbg.generated
     */
    public String getOutCarPlate() {
        return outCarPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.out_car_plate
     *
     * @param outCarPlate the value for park_in_out.out_car_plate
     *
     * @mbg.generated
     */
    public void setOutCarPlate(String outCarPlate) {
        this.outCarPlate = outCarPlate == null ? null : outCarPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.out_car_plate_color
     *
     * @return the value of park_in_out.out_car_plate_color
     *
     * @mbg.generated
     */
    public String getOutCarPlateColor() {
        return outCarPlateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.out_car_plate_color
     *
     * @param outCarPlateColor the value for park_in_out.out_car_plate_color
     *
     * @mbg.generated
     */
    public void setOutCarPlateColor(String outCarPlateColor) {
        this.outCarPlateColor = outCarPlateColor == null ? null : outCarPlateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.out_pic_path
     *
     * @return the value of park_in_out.out_pic_path
     *
     * @mbg.generated
     */
    public String getOutPicPath() {
        return outPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.out_pic_path
     *
     * @param outPicPath the value for park_in_out.out_pic_path
     *
     * @mbg.generated
     */
    public void setOutPicPath(String outPicPath) {
        this.outPicPath = outPicPath == null ? null : outPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.out_port_id
     *
     * @return the value of park_in_out.out_port_id
     *
     * @mbg.generated
     */
    public Integer getOutPortId() {
        return outPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.out_port_id
     *
     * @param outPortId the value for park_in_out.out_port_id
     *
     * @mbg.generated
     */
    public void setOutPortId(Integer outPortId) {
        this.outPortId = outPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.out_port_name
     *
     * @return the value of park_in_out.out_port_name
     *
     * @mbg.generated
     */
    public String getOutPortName() {
        return outPortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.out_port_name
     *
     * @param outPortName the value for park_in_out.out_port_name
     *
     * @mbg.generated
     */
    public void setOutPortName(String outPortName) {
        this.outPortName = outPortName == null ? null : outPortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.out_time
     *
     * @return the value of park_in_out.out_time
     *
     * @mbg.generated
     */
    public String getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.out_time
     *
     * @param outTime the value for park_in_out.out_time
     *
     * @mbg.generated
     */
    public void setOutTime(String outTime) {
        this.outTime = outTime == null ? null : outTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.out_type
     *
     * @return the value of park_in_out.out_type
     *
     * @mbg.generated
     */
    public Integer getOutType() {
        return outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.out_type
     *
     * @param outType the value for park_in_out.out_type
     *
     * @mbg.generated
     */
    public void setOutType(Integer outType) {
        this.outType = outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.park_id
     *
     * @return the value of park_in_out.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.park_id
     *
     * @param parkId the value for park_in_out.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column park_in_out.qpass_pay
     *
     * @return the value of park_in_out.qpass_pay
     *
     * @mbg.generated
     */
    public Double getQpassPay() {
        return qpassPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column park_in_out.qpass_pay
     *
     * @param qpassPay the value for park_in_out.qpass_pay
     *
     * @mbg.generated
     */
    public void setQpassPay(Double qpassPay) {
        this.qpassPay = qpassPay;
    }
}