package com.eparking.informationPush.entity.system;

public class RouteInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.ver_num
     *
     * @mbg.generated
     */
    private String verNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.server_ip
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.server_port
     *
     * @mbg.generated
     */
    private String serverPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.in_path
     *
     * @mbg.generated
     */
    private String inPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.out_path
     *
     * @mbg.generated
     */
    private String outPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.heart_path
     *
     * @mbg.generated
     */
    private String heartPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.static_path
     *
     * @mbg.generated
     */
    private String staticPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.dynamic_path
     *
     * @mbg.generated
     */
    private String dynamicPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.id
     *
     * @return the value of route_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.id
     *
     * @param id the value for route_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.name
     *
     * @return the value of route_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.name
     *
     * @param name the value for route_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.username
     *
     * @return the value of route_info.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.username
     *
     * @param username the value for route_info.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.password
     *
     * @return the value of route_info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.password
     *
     * @param password the value for route_info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.ver_num
     *
     * @return the value of route_info.ver_num
     *
     * @mbg.generated
     */
    public String getVerNum() {
        return verNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.ver_num
     *
     * @param verNum the value for route_info.ver_num
     *
     * @mbg.generated
     */
    public void setVerNum(String verNum) {
        this.verNum = verNum == null ? null : verNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.server_ip
     *
     * @return the value of route_info.server_ip
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.server_ip
     *
     * @param serverIp the value for route_info.server_ip
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.server_port
     *
     * @return the value of route_info.server_port
     *
     * @mbg.generated
     */
    public String getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.server_port
     *
     * @param serverPort the value for route_info.server_port
     *
     * @mbg.generated
     */
    public void setServerPort(String serverPort) {
        this.serverPort = serverPort == null ? null : serverPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.in_path
     *
     * @return the value of route_info.in_path
     *
     * @mbg.generated
     */
    public String getInPath() {
        return inPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.in_path
     *
     * @param inPath the value for route_info.in_path
     *
     * @mbg.generated
     */
    public void setInPath(String inPath) {
        this.inPath = inPath == null ? null : inPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.out_path
     *
     * @return the value of route_info.out_path
     *
     * @mbg.generated
     */
    public String getOutPath() {
        return outPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.out_path
     *
     * @param outPath the value for route_info.out_path
     *
     * @mbg.generated
     */
    public void setOutPath(String outPath) {
        this.outPath = outPath == null ? null : outPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.heart_path
     *
     * @return the value of route_info.heart_path
     *
     * @mbg.generated
     */
    public String getHeartPath() {
        return heartPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.heart_path
     *
     * @param heartPath the value for route_info.heart_path
     *
     * @mbg.generated
     */
    public void setHeartPath(String heartPath) {
        this.heartPath = heartPath == null ? null : heartPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.static_path
     *
     * @return the value of route_info.static_path
     *
     * @mbg.generated
     */
    public String getStaticPath() {
        return staticPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.static_path
     *
     * @param staticPath the value for route_info.static_path
     *
     * @mbg.generated
     */
    public void setStaticPath(String staticPath) {
        this.staticPath = staticPath == null ? null : staticPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.dynamic_path
     *
     * @return the value of route_info.dynamic_path
     *
     * @mbg.generated
     */
    public String getDynamicPath() {
        return dynamicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.dynamic_path
     *
     * @param dynamicPath the value for route_info.dynamic_path
     *
     * @mbg.generated
     */
    public void setDynamicPath(String dynamicPath) {
        this.dynamicPath = dynamicPath == null ? null : dynamicPath.trim();
    }
}