package com.eparking.informationPush.entity.system;

import java.util.ArrayList;
import java.util.List;

public class RouteInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table route_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table route_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table route_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public RouteInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table route_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andVerNumIsNull() {
            addCriterion("ver_num is null");
            return (Criteria) this;
        }

        public Criteria andVerNumIsNotNull() {
            addCriterion("ver_num is not null");
            return (Criteria) this;
        }

        public Criteria andVerNumEqualTo(String value) {
            addCriterion("ver_num =", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumNotEqualTo(String value) {
            addCriterion("ver_num <>", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumGreaterThan(String value) {
            addCriterion("ver_num >", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumGreaterThanOrEqualTo(String value) {
            addCriterion("ver_num >=", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumLessThan(String value) {
            addCriterion("ver_num <", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumLessThanOrEqualTo(String value) {
            addCriterion("ver_num <=", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumLike(String value) {
            addCriterion("ver_num like", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumNotLike(String value) {
            addCriterion("ver_num not like", value, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumIn(List<String> values) {
            addCriterion("ver_num in", values, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumNotIn(List<String> values) {
            addCriterion("ver_num not in", values, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumBetween(String value1, String value2) {
            addCriterion("ver_num between", value1, value2, "verNum");
            return (Criteria) this;
        }

        public Criteria andVerNumNotBetween(String value1, String value2) {
            addCriterion("ver_num not between", value1, value2, "verNum");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNull() {
            addCriterion("server_ip is null");
            return (Criteria) this;
        }

        public Criteria andServerIpIsNotNull() {
            addCriterion("server_ip is not null");
            return (Criteria) this;
        }

        public Criteria andServerIpEqualTo(String value) {
            addCriterion("server_ip =", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotEqualTo(String value) {
            addCriterion("server_ip <>", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThan(String value) {
            addCriterion("server_ip >", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("server_ip >=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThan(String value) {
            addCriterion("server_ip <", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLessThanOrEqualTo(String value) {
            addCriterion("server_ip <=", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpLike(String value) {
            addCriterion("server_ip like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotLike(String value) {
            addCriterion("server_ip not like", value, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpIn(List<String> values) {
            addCriterion("server_ip in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotIn(List<String> values) {
            addCriterion("server_ip not in", values, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpBetween(String value1, String value2) {
            addCriterion("server_ip between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerIpNotBetween(String value1, String value2) {
            addCriterion("server_ip not between", value1, value2, "serverIp");
            return (Criteria) this;
        }

        public Criteria andServerPortIsNull() {
            addCriterion("server_port is null");
            return (Criteria) this;
        }

        public Criteria andServerPortIsNotNull() {
            addCriterion("server_port is not null");
            return (Criteria) this;
        }

        public Criteria andServerPortEqualTo(String value) {
            addCriterion("server_port =", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortNotEqualTo(String value) {
            addCriterion("server_port <>", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortGreaterThan(String value) {
            addCriterion("server_port >", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortGreaterThanOrEqualTo(String value) {
            addCriterion("server_port >=", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortLessThan(String value) {
            addCriterion("server_port <", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortLessThanOrEqualTo(String value) {
            addCriterion("server_port <=", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortLike(String value) {
            addCriterion("server_port like", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortNotLike(String value) {
            addCriterion("server_port not like", value, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortIn(List<String> values) {
            addCriterion("server_port in", values, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortNotIn(List<String> values) {
            addCriterion("server_port not in", values, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortBetween(String value1, String value2) {
            addCriterion("server_port between", value1, value2, "serverPort");
            return (Criteria) this;
        }

        public Criteria andServerPortNotBetween(String value1, String value2) {
            addCriterion("server_port not between", value1, value2, "serverPort");
            return (Criteria) this;
        }

        public Criteria andInPathIsNull() {
            addCriterion("in_path is null");
            return (Criteria) this;
        }

        public Criteria andInPathIsNotNull() {
            addCriterion("in_path is not null");
            return (Criteria) this;
        }

        public Criteria andInPathEqualTo(String value) {
            addCriterion("in_path =", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathNotEqualTo(String value) {
            addCriterion("in_path <>", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathGreaterThan(String value) {
            addCriterion("in_path >", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathGreaterThanOrEqualTo(String value) {
            addCriterion("in_path >=", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathLessThan(String value) {
            addCriterion("in_path <", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathLessThanOrEqualTo(String value) {
            addCriterion("in_path <=", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathLike(String value) {
            addCriterion("in_path like", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathNotLike(String value) {
            addCriterion("in_path not like", value, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathIn(List<String> values) {
            addCriterion("in_path in", values, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathNotIn(List<String> values) {
            addCriterion("in_path not in", values, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathBetween(String value1, String value2) {
            addCriterion("in_path between", value1, value2, "inPath");
            return (Criteria) this;
        }

        public Criteria andInPathNotBetween(String value1, String value2) {
            addCriterion("in_path not between", value1, value2, "inPath");
            return (Criteria) this;
        }

        public Criteria andOutPathIsNull() {
            addCriterion("out_path is null");
            return (Criteria) this;
        }

        public Criteria andOutPathIsNotNull() {
            addCriterion("out_path is not null");
            return (Criteria) this;
        }

        public Criteria andOutPathEqualTo(String value) {
            addCriterion("out_path =", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathNotEqualTo(String value) {
            addCriterion("out_path <>", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathGreaterThan(String value) {
            addCriterion("out_path >", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathGreaterThanOrEqualTo(String value) {
            addCriterion("out_path >=", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathLessThan(String value) {
            addCriterion("out_path <", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathLessThanOrEqualTo(String value) {
            addCriterion("out_path <=", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathLike(String value) {
            addCriterion("out_path like", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathNotLike(String value) {
            addCriterion("out_path not like", value, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathIn(List<String> values) {
            addCriterion("out_path in", values, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathNotIn(List<String> values) {
            addCriterion("out_path not in", values, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathBetween(String value1, String value2) {
            addCriterion("out_path between", value1, value2, "outPath");
            return (Criteria) this;
        }

        public Criteria andOutPathNotBetween(String value1, String value2) {
            addCriterion("out_path not between", value1, value2, "outPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathIsNull() {
            addCriterion("heart_path is null");
            return (Criteria) this;
        }

        public Criteria andHeartPathIsNotNull() {
            addCriterion("heart_path is not null");
            return (Criteria) this;
        }

        public Criteria andHeartPathEqualTo(String value) {
            addCriterion("heart_path =", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathNotEqualTo(String value) {
            addCriterion("heart_path <>", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathGreaterThan(String value) {
            addCriterion("heart_path >", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathGreaterThanOrEqualTo(String value) {
            addCriterion("heart_path >=", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathLessThan(String value) {
            addCriterion("heart_path <", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathLessThanOrEqualTo(String value) {
            addCriterion("heart_path <=", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathLike(String value) {
            addCriterion("heart_path like", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathNotLike(String value) {
            addCriterion("heart_path not like", value, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathIn(List<String> values) {
            addCriterion("heart_path in", values, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathNotIn(List<String> values) {
            addCriterion("heart_path not in", values, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathBetween(String value1, String value2) {
            addCriterion("heart_path between", value1, value2, "heartPath");
            return (Criteria) this;
        }

        public Criteria andHeartPathNotBetween(String value1, String value2) {
            addCriterion("heart_path not between", value1, value2, "heartPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathIsNull() {
            addCriterion("static_path is null");
            return (Criteria) this;
        }

        public Criteria andStaticPathIsNotNull() {
            addCriterion("static_path is not null");
            return (Criteria) this;
        }

        public Criteria andStaticPathEqualTo(String value) {
            addCriterion("static_path =", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathNotEqualTo(String value) {
            addCriterion("static_path <>", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathGreaterThan(String value) {
            addCriterion("static_path >", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathGreaterThanOrEqualTo(String value) {
            addCriterion("static_path >=", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathLessThan(String value) {
            addCriterion("static_path <", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathLessThanOrEqualTo(String value) {
            addCriterion("static_path <=", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathLike(String value) {
            addCriterion("static_path like", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathNotLike(String value) {
            addCriterion("static_path not like", value, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathIn(List<String> values) {
            addCriterion("static_path in", values, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathNotIn(List<String> values) {
            addCriterion("static_path not in", values, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathBetween(String value1, String value2) {
            addCriterion("static_path between", value1, value2, "staticPath");
            return (Criteria) this;
        }

        public Criteria andStaticPathNotBetween(String value1, String value2) {
            addCriterion("static_path not between", value1, value2, "staticPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathIsNull() {
            addCriterion("dynamic_path is null");
            return (Criteria) this;
        }

        public Criteria andDynamicPathIsNotNull() {
            addCriterion("dynamic_path is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicPathEqualTo(String value) {
            addCriterion("dynamic_path =", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathNotEqualTo(String value) {
            addCriterion("dynamic_path <>", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathGreaterThan(String value) {
            addCriterion("dynamic_path >", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_path >=", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathLessThan(String value) {
            addCriterion("dynamic_path <", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathLessThanOrEqualTo(String value) {
            addCriterion("dynamic_path <=", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathLike(String value) {
            addCriterion("dynamic_path like", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathNotLike(String value) {
            addCriterion("dynamic_path not like", value, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathIn(List<String> values) {
            addCriterion("dynamic_path in", values, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathNotIn(List<String> values) {
            addCriterion("dynamic_path not in", values, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathBetween(String value1, String value2) {
            addCriterion("dynamic_path between", value1, value2, "dynamicPath");
            return (Criteria) this;
        }

        public Criteria andDynamicPathNotBetween(String value1, String value2) {
            addCriterion("dynamic_path not between", value1, value2, "dynamicPath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table route_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table route_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}